### ISSUE TITLE
使用此客户端与职业选手的对决

### ISSUE THREAD

**Issue by Dimension260** [baier233/Younkoo#3]
https://www.bilibili.com/video/av1206291829?p=1&unique_k=2333
作者你好，你可以看看这个视频，这是我用你的开源项目和主播的剪辑

**Comment by baier233** [comment]
扣1送正版younkoo

**Comment by Dimension260** [comment]
> 扣1送正版younkoo

111真的吗主播，可以换地狱火吗😃

**Comment by baier233** [comment]
> > 扣1送正版younkoo
> 
> 111真的吗主播，可以换地狱火吗😃

真,发个联系方式

**Comment by Dimension260** [comment]
QQ:2602717346

**Comment by baier233** [comment]
加不上，3237714486

**Comment by Dimension260** [comment]
好了，可以加了
